# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fit Buddies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fit Buddies
  
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/OAuth'
  pod 'GoogleSignIn'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI/Storage'
  
  pod “FBSDKCoreKit”
  pod “FBSDKLoginKit”
  pod “FBSDKShareKit”

end
